/**
 * Import will remove at compile time
 */

import type { FormatDiagnosticsHost } from 'typescript';

/**
 * Imports
 */

import { sys } from 'typescript';

/**
 * A host object that provides formatting functionality for TypeScript diagnostic messages.
 *
 * @remarks
 * This constant implements the {@link FormatDiagnosticsHost} interface from TypeScript,
 * providing methods needed for proper diagnostic message formatting. It uses TypeScript's
 * built-in system utilities for platform-specific formatting operations.
 *
 * The host provides:
 * - Line break characters appropriate for the current platform
 * - Current working directory information
 * - File name canonicalization (case-sensitive or insensitive based on a platform)
 *
 * @example
 * ```ts
 * import ts from 'typescript';
 * import { formatHost } from './typescript.constant';
 *
 * const diagnostics = ts.getPreEmitDiagnostics(program);
 * const formatted = ts.formatDiagnosticsWithColorAndContext(diagnostics, formatHost);
 * console.log(formatted);
 * ```
 *
 * @see FormatDiagnosticsHost
 * @since 1.5.9
 */

export const formatHost: FormatDiagnosticsHost = {
    getNewLine: () => sys.newLine,
    getCurrentDirectory: sys.getCurrentDirectory,
    getCanonicalFileName: (fileName) => sys.useCaseSensitiveFileNames ? fileName : fileName.toLowerCase()
} as const;

/**
 * Header text included at the top of generated declaration bundle files.
 *
 * @remarks
 * This constant provides a standardized header comment prepended to all
 * declaration bundle files generated by the TypeScript module. The header clearly
 * indicates that the file was automatically generated and should not be edited manually.
 *
 * The header serves as:
 * - A warning to developers not to manually modify generated files
 * - Documentation indicating the source of the file
 * - A consistent marker for identifying generated declaration files
 *
 * @example
 * ```ts
 * import { HeaderDeclarationBundle } from './typescript.constant';
 * import { writeFileSync } from 'fs';
 *
 * const bundledContent = `${HeaderDeclarationBundle}\n${actualDeclarations}`;
 * writeFileSync('dist/index.d.ts', bundledContent);
 * ```
 *
 * @since 1.5.9
 */

export const HeaderDeclarationBundle = `/**
 * This file was automatically generated by xBuild.
 * DO NOT EDIT MANUALLY.
 */
`;
