/**
 * Import will remove at compile time
 */

import type { FilesModel } from '@typescript/models/files.model';
import type { FrameworkService } from '@services/framework.service';

/**
 * Structured result of a parsed and formatted stack trace.
 *
 * @remarks
 * This interface represents the finalized output from stack trace parsing and formatting,
 * containing both the raw code context and fully formatted stack frames ready for display.
 * Used as the return type for {@link getErrorMetadata}.
 *
 * @see getErrorMetadata
 * @since 2.0.0
 */

export interface StackInterface {
    /**
     * Extracted source code snippet surrounding the error location.
     *
     * @remarks
     * Contains multiple lines of code context (before and after the error line)
     * as determined by the {@link StackTraceInterface.linesBefore} and
     * {@link StackTraceInterface.linesAfter} options.
     *
     * @since 2.0.0
     */

    code: string;

    /**
     * Line number of the error within the source file.
     *
     * @remarks
     * This line number reflects the original source position after source map resolution,
     * with any {@link StackContextInterface.lineOffset} applied.
     *
     * @since 2.0.0
     */

    line: number;

    /**
     * Column number of the error within the source file.
     *
     * @remarks
     * This column number reflects the original source position after source map resolution.
     *
     * @since 2.0.0
     */

    column: number;

    /**
     * Original source file path, if available.
     *
     * @remarks
     * This is the resolved source file path from source maps or the original file name.
     * May be undefined if no source information is available.
     *
     * @since 2.0.0
     */

    source?: string;

    /**
     * Array of formatted stack trace entries ready for display.
     *
     * @remarks
     * Each string represents a single formatted stack frame, complete with
     * function names, file paths, line/column numbers, and color formatting.
     * Empty strings from filtered frames (native or framework) are excluded.
     *
     * @since 2.0.0
     */

    stacks: Array<string>;

    /**
     * Syntax-highlighted and formatted version of the source code snippet.
     *
     * @remarks
     * Contains the {@link code} with applied syntax highlighting and error formatting,
     * including line numbers and a marker indicating the exact error position.
     * Generated by {@link highlightPositionCode} and cached during frame processing.
     *
     * @see highlightPositionCode
     * @since 2.0.0
     */

    formatCode: string;
}

/**
 * Configuration options for parsing and formatting stack traces.
 *
 * @remarks
 * These options control how stack traces are parsed, what frames are included,
 * and how much source code context is displayed. Used by {@link getErrorMetadata}
 * and {@link stackEntry} to customize stack trace output.
 *
 * @see stackEntry
 * @see getErrorMetadata
 *
 * @since 2.0.0
 */

export interface StackTraceInterface {
    /**
     * Number of lines of source code to include after the error line.
     *
     * @defaultValue 3
     *
     * @remarks
     * Defaults to 3 if not specified. Used when extracting code context
     * from source files or snapshots.
     *
     * @since 2.0.0
     */

    linesAfter?: number;

    /**
     * Number of lines of source code to include before the error line.
     *
     * @defaultValue 3
     *
     * @remarks
     * Defaults to 3 if not specified. Used when extracting code context
     * from source files or snapshots.
     *
     * @since 2.0.0
     */

    linesBefore?: number;

    /**
     * Whether to include native (built-in) stack frames in the output.
     *
     * @defaultValue Based on `ConfigurationService.verbose` setting
     *
     * @remarks
     * Native frames are those marked with `frame.native === true`, typically
     * representing Node.js internal functions. When false, these frames are
     * filtered out during processing. Automatically set based on the `verbose`
     * configuration setting if not explicitly provided.
     *
     * @since 2.0.0
     */

    withNativeFrames?: boolean;

    /**
     * Whether to include framework-internal stack frames in the output.
     *
     * @defaultValue Based on `ConfigurationService.verbose` setting
     *
     * @remarks
     * Framework frames are identified by {@link FrameworkService.isFrameworkFile}.
     * When false, these frames are filtered out to reduce noise in stack traces.
     * Automatically set based on the `verbose` configuration setting if not
     * explicitly provided.
     *
     * @see FrameworkService.isFrameworkFile
     * @since 2.0.0
     */

    withFrameworkFrames?: boolean;
}

/**
 * Internal runtime context used during stack trace parsing and formatting.
 *
 * @remarks
 * This context extends {@link StackTraceInterface} with additional runtime state
 * and service dependencies required during stack trace processing. It maintains
 * mutable state as frames are processed, including the first encountered code snippet,
 * line/column positions, and formatted output. Used internally by {@link stackEntry},
 * {@link formatFrameWithPosition}, and related functions.
 *
 * @see stackEntry
 * @see getErrorMetadata
 * @see StackTraceInterface
 *
 * @since 2.0.0
 */

export interface StackContextInterface extends StackTraceInterface {
    /**
     * Cached source code snippet from the first processed frame with code context.
     *
     * @remarks
     * Populated by {@link formatFrameWithPosition} on the first frame that has
     * available code. Subsequent frames do not overwrite this value, ensuring
     * the code displayed corresponds to the most relevant stack frame.
     *
     * @see formatFrameWithPosition
     *
     * @since 2.0.0
     */

    code: string;

    /**
     * Reference to the {@link FilesModel} service for accessing file snapshots.
     *
     * @remarks
     * Used by {@link getSource} to retrieve file content when source maps are
     * not available. Injected during context initialization in {@link getErrorMetadata}.
     *
     * @see getSource
     * @see FilesModel
     *
     * @since 2.0.0
     */

    files: FilesModel;

    /**
     * Cached original source file path from the first processed frame.
     *
     * @remarks
     * Populated by {@link formatFrameWithPosition} on the first frame that has
     * a resolved source position. Corresponds to the file containing the {@link code}.
     *
     * @see formatFrameWithPosition
     * @since 2.0.0
     */

    source: string;

    /**
     * Reference to the {@link FrameworkService} for resolving source maps and framework files.
     *
     * @remarks
     * Used throughout stack processing to:
     * - Retrieve source maps via {@link FrameworkService.getSourceMap}
     * - Identify framework files via {@link FrameworkService.isFrameworkFile}
     * - Resolve relative paths using {@link FrameworkService.rootPath}
     *
     * Injected during context initialization in {@link getErrorMetadata}.
     *
     * @see getSource
     * @see stackEntry
     * @see FrameworkService
     *
     * @since 2.0.0
     */

    framework: FrameworkService;

    /**
     * Resolved line number from the most recently processed stack frame.
     *
     * @remarks
     * Updated by {@link stackEntry} after resolving source positions.
     * Includes any {@link lineOffset} adjustments. Used to populate the
     * final {@link StackInterface.line} value.
     *
     * @see stackEntry
     * @since 2.0.0
     */

    line: number;

    /**
     * Resolved column number from the most recently processed stack frame.
     *
     * @remarks
     * Updated by {@link stackEntry} after resolving source positions.
     * Used to populate the final {@link StackInterface.column} value.
     *
     * @see stackEntry
     * @since 2.0.0
     */

    column: number;

    /**
     * Line number offset to apply to all resolved positions.
     *
     * @defaultValue 0
     *
     * @remarks
     * Applied to `position.line`, `position.startLine`, and `position.endLine`
     * in {@link stackEntry}. Useful for aligning stack trace line numbers with
     * external systems or editors that use different line numbering schemes.
     *
     * @see stackEntry
     * @since 2.0.0
     */

    lineOffset: number;

    /**
     * Cached syntax-highlighted code snippet from the first processed frame.
     *
     * @remarks
     * Generated by {@link highlightPositionCode} and stored by {@link formatFrameWithPosition}
     * on the first frame that has code context. This is the display-ready version of {@link code}
     * with syntax highlighting, line numbers, and error position markers applied.
     *
     * @see highlightPositionCode
     * @see formatFrameWithPosition
     *
     * @since 2.0.0
     */

    formatCode: string;
}
